import type { z } from "zod";
import * as wire from "../index";

/**
 * Every wire schema covered by the additive-only compat check. Add new
 * top-level schemas here as they're introduced — the fixture in
 * `__fixtures__/wire-shapes.json` is regenerated (never hand-edited) by
 * `scripts/snapshot-shapes.ts` once a schema's shape is ready to freeze.
 */
export const schemaRegistry: Record<string, z.ZodTypeAny> = {
  EncryptedBoxSchema: wire.EncryptedBoxSchema,
  PermissionModeSchema: wire.PermissionModeSchema,
  PermDecisionSchema: wire.PermDecisionSchema,
  SessionEventSchema: wire.SessionEventSchema,
  SessionEnvelopeSchema: wire.SessionEnvelopeSchema,
  SessionRowSchema: wire.SessionRowSchema,
  MachineRowSchema: wire.MachineRowSchema,
  UnmanagedSessionRowSchema: wire.UnmanagedSessionRowSchema,
  UpdateSchema: wire.UpdateSchema,
  EphemeralSchema: wire.EphemeralSchema,
  RpcCallSchema: wire.RpcCallSchema,
  SpawnParamsSchema: wire.SpawnParamsSchema,
  SpawnResultSchema: wire.SpawnResultSchema,
  StopSessionParamsSchema: wire.StopSessionParamsSchema,
  StopSessionResultSchema: wire.StopSessionResultSchema,
  ResumeSessionParamsSchema: wire.ResumeSessionParamsSchema,
  ResumeSessionResultSchema: wire.ResumeSessionResultSchema,
  ListSessionsResultSchema: wire.ListSessionsResultSchema,
  GitStatusParamsSchema: wire.GitStatusParamsSchema,
  GitStatusResultSchema: wire.GitStatusResultSchema,
  GitDiffParamsSchema: wire.GitDiffParamsSchema,
  GitDiffResultSchema: wire.GitDiffResultSchema,
  GitBranchesParamsSchema: wire.GitBranchesParamsSchema,
  GitBranchInfoSchema: wire.GitBranchInfoSchema,
  GitBranchesResultSchema: wire.GitBranchesResultSchema,
  GitFilesParamsSchema: wire.GitFilesParamsSchema,
  GitFilesResultSchema: wire.GitFilesResultSchema,
  GitCommitParamsSchema: wire.GitCommitParamsSchema,
  GitCommitResultSchema: wire.GitCommitResultSchema,
  GitPushParamsSchema: wire.GitPushParamsSchema,
  GitPushResultSchema: wire.GitPushResultSchema,
  GitRenameBranchParamsSchema: wire.GitRenameBranchParamsSchema,
  GitRenameBranchResultSchema: wire.GitRenameBranchResultSchema,
  GithubChecksParamsSchema: wire.GithubChecksParamsSchema,
  CheckRunSchema: wire.CheckRunSchema,
  PullRequestInfoSchema: wire.PullRequestInfoSchema,
  GithubChecksResultSchema: wire.GithubChecksResultSchema,
  SlashCommandsListParamsSchema: wire.SlashCommandsListParamsSchema,
  SlashCommandInfoSchema: wire.SlashCommandInfoSchema,
  SlashCommandsListResultSchema: wire.SlashCommandsListResultSchema,
  ProviderAccountParamsSchema: wire.ProviderAccountParamsSchema,
  ProviderUsageMeterSchema: wire.ProviderUsageMeterSchema,
  ProviderAccountResultSchema: wire.ProviderAccountResultSchema,
  FsReadParamsSchema: wire.FsReadParamsSchema,
  FsReadResultSchema: wire.FsReadResultSchema,
  FsListParamsSchema: wire.FsListParamsSchema,
  FsListResultSchema: wire.FsListResultSchema,
  FsMkdirParamsSchema: wire.FsMkdirParamsSchema,
  FsMkdirResultSchema: wire.FsMkdirResultSchema,
  WorkspaceRegisterParamsSchema: wire.WorkspaceRegisterParamsSchema,
  WorkspaceRegisterResultSchema: wire.WorkspaceRegisterResultSchema,
  AdoptListParamsSchema: wire.AdoptListParamsSchema,
  AdoptListResultSchema: wire.AdoptListResultSchema,
  AdoptTakeParamsSchema: wire.AdoptTakeParamsSchema,
  AdoptTakeResultSchema: wire.AdoptTakeResultSchema,
  AdoptMirrorParamsSchema: wire.AdoptMirrorParamsSchema,
  AdoptMirrorResultSchema: wire.AdoptMirrorResultSchema,
  SleepInhibitModeSchema: wire.SleepInhibitModeSchema,
  SleepInhibitStateSchema: wire.SleepInhibitStateSchema,
  SleepInhibitGetParamsSchema: wire.SleepInhibitGetParamsSchema,
  SleepInhibitSetParamsSchema: wire.SleepInhibitSetParamsSchema,
  MessageRpcParamsSchema: wire.MessageRpcParamsSchema,
  MessageRpcResultSchema: wire.MessageRpcResultSchema,
  MessageRpcStatusSchema: wire.MessageRpcStatusSchema,
  PermAnswerParamsSchema: wire.PermAnswerParamsSchema,
  PermAnswerResultSchema: wire.PermAnswerResultSchema,
  InterruptResultSchema: wire.InterruptResultSchema,
  StopRpcParamsSchema: wire.StopRpcParamsSchema,
  StopRpcResultSchema: wire.StopRpcResultSchema,
  TakeControlResultSchema: wire.TakeControlResultSchema,
  SetModeParamsSchema: wire.SetModeParamsSchema,
  SetModeResultSchema: wire.SetModeResultSchema,
  LifecycleKindSchema: wire.LifecycleKindSchema,
  PushChannelSchema: wire.PushChannelSchema,
  PushSubscribeBodySchema: wire.PushSubscribeBodySchema,
  PushUnsubscribeBodySchema: wire.PushUnsubscribeBodySchema,
  PushPayloadSchema: wire.PushPayloadSchema,
  BlobRequestUploadBodySchema: wire.BlobRequestUploadBodySchema,
  BlobRequestUploadResultSchema: wire.BlobRequestUploadResultSchema,
  BlobRequestDownloadBodySchema: wire.BlobRequestDownloadBodySchema,
  BlobRequestDownloadResultSchema: wire.BlobRequestDownloadResultSchema,
  PreviewPortsParamsSchema: wire.PreviewPortsParamsSchema,
  PreviewPortInfoSchema: wire.PreviewPortInfoSchema,
  PreviewPortsResultSchema: wire.PreviewPortsResultSchema,
  PreviewTunnelsParamsSchema: wire.PreviewTunnelsParamsSchema,
  TunnelInfoSchema: wire.TunnelInfoSchema,
  PreviewTunnelsResultSchema: wire.PreviewTunnelsResultSchema,
  PreviewOpenParamsSchema: wire.PreviewOpenParamsSchema,
  PreviewOpenResultSchema: wire.PreviewOpenResultSchema,
  PreviewCloseParamsSchema: wire.PreviewCloseParamsSchema,
  PreviewCloseResultSchema: wire.PreviewCloseResultSchema,
  WorkspaceGetConfigParamsSchema: wire.WorkspaceGetConfigParamsSchema,
  WorkspaceGetConfigResultSchema: wire.WorkspaceGetConfigResultSchema,
  RunStartParamsSchema: wire.RunStartParamsSchema,
  RunStartResultSchema: wire.RunStartResultSchema,
  RunStopParamsSchema: wire.RunStopParamsSchema,
  RunStopResultSchema: wire.RunStopResultSchema,
  RunStatusParamsSchema: wire.RunStatusParamsSchema,
  RunStatusResultSchema: wire.RunStatusResultSchema,
  RunSetupParamsSchema: wire.RunSetupParamsSchema,
  RunSetupResultSchema: wire.RunSetupResultSchema,
};
