import type { RenderItem } from "@/sync/reducer";

/**
 * A hand-built `RenderItem[]` covering every kind the reducer can emit
 * (`sync/reducer/types.ts`) plus every `ToolCard` registry entry
 * (`tool-cards/registry.tsx`). Stands in for the real sync engine — which
 * is a separate, still-in-flight task (plan.md §8.1) — so this screen is
 * reviewable end-to-end today. Swap `SessionTimelineScreen`'s data source
 * for live `RenderItem[]` once that lands; nothing else here changes.
 */
export const demoRenderItems: RenderItem[] = [
  {
    id: "e1",
    time: 1000,
    role: "user",
    kind: "text",
    md: "Can you check why the flaky test in `sum.test.ts` fails sometimes, and fix it if it's a race condition?",
    thinking: false,
  },
  {
    id: "e2",
    time: 1001,
    role: "agent",
    turn: "turn-1",
    kind: "turn-start",
  },
  {
    id: "e3",
    time: 1002,
    role: "agent",
    turn: "turn-1",
    kind: "text",
    md: "The test asserts on `Date.now()` twice without freezing the clock, so under load the two calls can land in different milliseconds. I should look at the test file and the module it covers, then fix the assertion.",
    thinking: true,
  },
  {
    id: "e4",
    time: 1003,
    role: "agent",
    turn: "turn-1",
    kind: "tool",
    call: "call-read-1",
    name: "Read",
    args: { file_path: "src/sum.test.ts" },
    status: "done",
    ok: true,
    output:
      'import { describe, expect, it } from "vitest";\nimport { sum } from "./sum";\n\ndescribe("sum", () => {\n  it("is deterministic", () => {\n    expect(sum(1, 2)).toBe(Date.now() - Date.now() + 3);\n  });\n});\n',
  },
  {
    id: "e5",
    time: 1004,
    role: "agent",
    turn: "turn-1",
    kind: "tool",
    call: "call-grep-1",
    name: "Grep",
    args: { pattern: "Date.now", path: "src", glob: "*.test.ts" },
    status: "done",
    ok: true,
    output: ["src/sum.test.ts:6"],
  },
  {
    id: "e6",
    time: 1005,
    role: "agent",
    turn: "turn-1",
    kind: "text",
    md: "Found it — the assertion subtracts two live `Date.now()` calls instead of using a constant. Fixing it now.",
    thinking: false,
  },
  {
    id: "e7",
    time: 1006,
    role: "agent",
    turn: "turn-1",
    kind: "perm-placeholder",
    name: "Edit",
    args: { file_path: "src/sum.test.ts" },
    permission: { reqId: "req-1", modes: ["default", "acceptEdits"] },
  },
  {
    id: "e8",
    time: 1007,
    role: "agent",
    turn: "turn-1",
    kind: "tool",
    call: "call-edit-1",
    name: "Edit",
    title: "Edit sum.test.ts",
    args: {
      file_path: "src/sum.test.ts",
      old_string: "    expect(sum(1, 2)).toBe(Date.now() - Date.now() + 3);",
      new_string: "    expect(sum(1, 2)).toBe(3);",
    },
    risk: "write",
    status: "done",
    ok: true,
    permission: {
      reqId: "req-1",
      modes: ["default", "acceptEdits"],
      decision: { kind: "allow", scope: "once" },
    },
  },
  {
    id: "e9",
    time: 1008,
    role: "agent",
    turn: "turn-1",
    kind: "tool",
    call: "task-1",
    name: "Task",
    title: "Run the full test suite",
    args: { description: "Verify the fix", prompt: "Run `pnpm test` and report pass/fail." },
    status: "done",
    ok: true,
    output: { summary: "42/42 tests passing" },
    subagent: [
      { id: "s1", time: 1008.1, role: "agent", turn: "turn-1", kind: "sub-start" },
      {
        id: "s2",
        time: 1008.2,
        role: "agent",
        turn: "turn-1",
        kind: "tool",
        call: "call-bash-1",
        name: "Bash",
        args: { command: "pnpm test", description: "Run the test suite" },
        risk: "exec",
        status: "done",
        ok: true,
        output: {
          stdout:
            "✓ src/sum.test.ts (1 test)\n\n Test Files  1 passed (1)\n      Tests  1 passed (1)\n",
          stderr: "",
        },
      },
      { id: "s3", time: 1008.3, role: "agent", turn: "turn-1", kind: "sub-stop" },
    ],
  },
  {
    id: "e10",
    time: 1009,
    role: "agent",
    turn: "turn-1",
    kind: "tool",
    call: "call-todo-1",
    name: "TodoWrite",
    args: {
      todos: [
        {
          content: "Reproduce the flaky assertion",
          status: "completed",
          activeForm: "Reproducing",
        },
        { content: "Fix the race condition", status: "completed", activeForm: "Fixing" },
        { content: "Re-run the suite", status: "in_progress", activeForm: "Re-running" },
      ],
    },
    status: "done",
    ok: true,
  },
  {
    id: "e11",
    time: 1010,
    role: "agent",
    turn: "turn-1",
    kind: "tool",
    call: "call-mcp-1",
    name: "mcp__linear__create_comment",
    title: "Comment on FAL-142",
    args: { issueId: "FAL-142", body: "Fixed the flaky clock assertion in sum.test.ts." },
    status: "done",
    ok: true,
    output: { id: "comment_9f2", url: "https://linear.app/falcon/issue/FAL-142#comment-9f2" },
  },
  {
    id: "e12",
    time: 1011,
    role: "agent",
    turn: "turn-1",
    kind: "orphan-tool-end",
    call: "call-webfetch-0",
    ok: false,
    output: { error: "ETIMEDOUT" },
  },
  {
    id: "e13",
    time: 1012,
    role: "agent",
    turn: "turn-1",
    kind: "file",
    ref: "blob:coverage-report",
    name: "coverage-summary.png",
    size: 48213,
    image: { w: 960, h: 540, thumbhash: "1QcSHQRnh493V4dIh4eXh1h4kJUI" },
  },
  {
    id: "e14",
    time: 1013,
    role: "agent",
    turn: "turn-1",
    kind: "service",
    text: "Context compacted (18,204 tokens summarized).",
  },
  {
    id: "e15",
    time: 1014,
    role: "agent",
    kind: "mode-switch",
    control: "remote",
    by: "client",
  },
  {
    id: "e16",
    time: 1015,
    role: "agent",
    turn: "turn-1",
    kind: "turn-end",
    status: "completed",
  },
  {
    id: "e17",
    time: 1016,
    role: "user",
    kind: "text",
    md: "Nice. One more thing — can you also add a changelog entry?",
    thinking: false,
  },
  {
    id: "e18",
    time: 1017,
    role: "agent",
    turn: "turn-2",
    kind: "tool",
    call: "call-write-1",
    name: "Write",
    args: {
      file_path: "CHANGELOG.md",
      content: "## Unreleased\n\n- Fix flaky clock assertion in `sum.test.ts`.\n",
    },
    risk: "write",
    status: "running",
  },
  {
    id: "e19",
    time: 1018,
    role: "agent",
    turn: "turn-2",
    kind: "turn-end",
    status: "cancelled",
  },
  {
    id: "e20",
    time: 1019,
    role: "agent",
    kind: "subagent-group",
    subagentId: "orphan-subagent-1",
    items: [
      {
        id: "o1",
        time: 1019.1,
        role: "agent",
        kind: "text",
        md: "(This subagent's parent `Task` call fell outside the loaded history — its work still shows up here.)",
        thinking: false,
      },
    ],
  },
];
