/**
 * Installer for Falcon's managed ACP adapter packages (design §7.9). Never
 * `npx` at session start: this runs a real `npm install <pkg>@<exact
 * version>` into `~/.falcon/adapters/` — its own npm prefix, separate from
 * both the user's global npm and Falcon's own `node_modules` — and then
 * re-verifies the result against `ADAPTER_MANIFEST` (`verify.ts`) before
 * reporting success. A version or integrity mismatch after install throws
 * `AdapterIntegrityError` rather than silently reporting success — the
 * install genuinely didn't produce what Falcon shipped a hash for.
 *
 * Deliberate design choice, spelled out here rather than left implicit: the
 * manifest pins only the *target* package's own version + integrity, not a
 * full hand-authored lockfile for its entire transitive dependency tree.
 * `npm ci` against a hand-written full lockfile was evaluated and rejected —
 * it requires the lockfile to exactly describe every transitive/optional
 * dependency (verified empirically against the real
 * `@agentclientprotocol/claude-agent-acp` tree), which would go stale the
 * moment any transitive dependency published a patch release, entirely
 * independent of Falcon's own release cycle. Installing normally and then
 * comparing the resulting `node_modules/.package-lock.json` entry for the
 * top-level package against our pinned manifest value (`verify.ts`) is
 * simpler, survives transitive churn, and still catches the case that
 * actually matters: the registry serving different bytes than what Falcon's
 * release was tested against under the same package@version.
 */

import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import type { AdapterId } from "./manifest.js";
import { ADAPTER_MANIFEST } from "./manifest.js";
import { adaptersDir, adaptersPackageJsonPath } from "./paths.js";
import { verifyAdapterInstall } from "./verify.js";

export class AdapterInstallError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "AdapterInstallError";
  }
}

export class AdapterIntegrityError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "AdapterIntegrityError";
  }
}

/** Runs `npm <args>` in `cwd`. Injectable — tests never shell out to a real `npm install`. */
export type NpmExec = (args: string[], cwd: string) => Promise<void>;

export const runNpm: NpmExec = (args, cwd) =>
  new Promise((resolve, reject) => {
    execFile("npm", args, { cwd, maxBuffer: 20 * 1024 * 1024 }, (error, _stdout, stderr) => {
      if (error) {
        reject(new AdapterInstallError(stderr.toString().trim() || error.message));
        return;
      }
      resolve();
    });
  });

export interface AdapterInstallDeps {
  homeDir: string;
  runNpm?: NpmExec;
}

export type AdapterInstallStatus = "already-satisfied" | "installed" | "reinstalled";

export type AdapterInstallOutcome =
  | { id: AdapterId; ok: true; status: AdapterInstallStatus; version: string; path: string }
  | { id: AdapterId; ok: false; error: string };

async function ensureRootPackageJson(homeDir: string): Promise<void> {
  await mkdir(adaptersDir(homeDir), { recursive: true });
  const file = adaptersPackageJsonPath(homeDir);
  if (existsSync(file)) return;
  const pkg = {
    name: "falcon-adapters",
    private: true,
    version: "1.0.0",
    description:
      "Managed ACP adapter installs (falcon-system-design.md §7.9) — do not edit by hand; regenerated by `falcon adapters install|upgrade`.",
  };
  await writeFile(file, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
}

/**
 * Installs (or, with `force: true`, force-reinstalls) a single pinned
 * adapter. Idempotent by default: if the currently-installed package
 * already matches the manifest's version + integrity, this is a no-op that
 * reports `"already-satisfied"` without touching the network.
 */
export async function installAdapter(
  id: AdapterId,
  deps: AdapterInstallDeps,
  opts: { force?: boolean } = {},
): Promise<AdapterInstallOutcome> {
  const entry = ADAPTER_MANIFEST[id];
  const npm = deps.runNpm ?? runNpm;

  try {
    await ensureRootPackageJson(deps.homeDir);

    if (!opts.force) {
      const already = await verifyAdapterInstall(id, deps.homeDir);
      if (already.ok) {
        return {
          id,
          ok: true,
          status: "already-satisfied",
          version: already.version,
          path: already.entryPath,
        };
      }
    }

    await npm(
      [
        "install",
        `${entry.packageName}@${entry.version}`,
        "--save-exact",
        "--omit=dev",
        "--no-audit",
        "--no-fund",
      ],
      adaptersDir(deps.homeDir),
    );

    const verified = await verifyAdapterInstall(id, deps.homeDir);
    if (!verified.ok) {
      throw new AdapterIntegrityError(
        `${entry.packageName}@${entry.version} failed integrity verification after install (${verified.reason}${
          verified.detail ? `: ${verified.detail}` : ""
        })`,
      );
    }

    return {
      id,
      ok: true,
      status: opts.force ? "reinstalled" : "installed",
      version: verified.version,
      path: verified.entryPath,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { id, ok: false, error: message };
  }
}

/**
 * Installs (or force-reinstalls) every adapter in `ADAPTER_MANIFEST`.
 * Each adapter is isolated — one failing install (e.g. a transient registry
 * error for `codex-acp`) never prevents the others from installing, and the
 * full per-adapter outcome list is always returned rather than throwing on
 * the first failure, so the caller (the `falcon adapters` CLI command,
 * or an automatic first-run install) can report every result.
 */
export async function installAllAdapters(
  deps: AdapterInstallDeps,
  opts: { force?: boolean } = {},
): Promise<AdapterInstallOutcome[]> {
  const ids = Object.keys(ADAPTER_MANIFEST) as AdapterId[];
  const outcomes: AdapterInstallOutcome[] = [];
  for (const id of ids) {
    outcomes.push(await installAdapter(id, deps, opts));
  }
  return outcomes;
}
